CREATE SCHEMA `bank2` ;


CREATE TABLE CUSTOMER(CUSTOMER_ID VARCHAR(15) NOT NULL,CUSTOMER_NAME VARCHAR(15) NOT NULL,CUSTOMER_STREET VARCHAR(15) 
NOT NULL,CUSTOMER_CITY VARCHAR(15) NOT NULL,PRIMARY KEY(CUSTOMER_ID) ) ;

CREATE TABLE BRANCH(BRANCH_NAME VARCHAR(15) NOT NULL,BRANCH_CITY VARCHAR(15) NOT NULL,ASSETS VARCHAR(15) NOT 
NULL,PRIMARY KEY(BRANCH_NAME) ) ;

CREATE TABLE LOAN(LOAN_NUMBER NUMERIC(10) NOT NULL,AMOUNT NUMERIC(15) NOT NULL,PRIMARY KEY(LOAN_NUMBER) ) ;

CREATE TABLE EMPLOYEE(EMPLOYEE_ID 

VARCHAR(15) NOT NULL,EMPLOYEE_NAME 

VARCHAR(15) NOT NULL,CUSTOMER_STREET 

VARCHAR(15) 
NOT NULL,START_DATE 
 DATENOT NULL,PRIMARY KEY (EMPLOYEE_ID) ) ;

CREATE TABLE  EMPLOYEEPHONE( EMPLOYEE_ID VARCHAR(15) NOT NULL,PHONE_NUMBER VARCHAR(10),
                       PRIMARY KEY 
(EMPLOYEE_ID),FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)) ; 


CREATE TABLE  EMPLOYEEDEPARTMENT( EMPLOYEE_ID VARCHAR(15) NOT NULL,DEPARTMENT VARCHAR(10),
                       PRIMARY KEY 
(EMPLOYEE_ID),FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)) ; 


CREATE TABLE BORROWER(CUSTOMER_ID 

VARCHAR(15) NOT NULL,LOAN_NUMBER NUMERIC(10) 

NOT NULL,PRIMARY KEY(CUSTOMER_ID 
,LOAN_NUMBER),FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
 FOREIGN KEY(LOAN_NUMBER) REFERENCES LOAN
(LOAN_NUMBER)) ;


CREATE TABLE CUST_BANKER(BANKER_TYPE VARCHAR(15) NOT NULL,CUSTOMER_ID VARCHAR(15) NOT NULL,
EMPLOYEE_ID VARCHAR(15) NOT 
NULL,PRIMARY KEY(CUSTOMER_ID),FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)) ;


CREATE TABLE LOAN_BRANCH(LOAN_NUMBER NUMERIC(10) NOT NULL,BRANCH_NAME VARCHAR(15) NOT NULL,
PRIMARY KEY(LOAN_NUMBER) 
,FOREIGN KEY (LOAN_NUMBER) REFERENCES LOAN(LOAN_NUMBER)) ;


CREATE TABLE _ACCOUNT(ACCOUNT_ID VARCHAR(20) NOT NULL,BALANCE VARCHAR(20) NOT NULL,
PRIMARY KEY(ACCOUNT_ID)) ;


CREATE TABLE  SAVING_ACCOUNT(ACCOUNT_ID VARCHAR(20) NOT NULL,INTEREST_RATE VARCHAR(20) NOT NULL,
PRIMARY KEY(ACCOUNT_ID)) 
;


CREATE TABLE  CHECKING_ACCOUNT(ACCOUNT_ID VARCHAR(20) NOT NULL,OVERDRAFT_AMOUNT VARCHAR(20) NOT NULL,
PRIMARY KEY
(ACCOUNT_ID)) ;


CREATE TABLE  ACCOUNT_BRANCH(ACCOUNT_ID VARCHAR(20) NOT NULL,BRANCH_NAME VARCHAR(15) NOT NULL,
PRIMARY KEY(ACCOUNT_ID)) 
;



CREATE TABLE  DEPOSITOR(ACCESS_DATE DATE NOT NULL ,ACCOUNT_ID VARCHAR(20) NOT NULL,
CUSTOMER_ID VARCHAR(15) NOT 
NULL,PRIMARY KEY(CUSTOMER_ID,ACCOUNT_ID),
FOREIGN KEY(ACCOUNT_ID) REFERENCES _ACCOUNT(ACCOUNT_ID),FOREIGN KEY
(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));



CREATE TABLE PAYMENT(LOAN_NUMBER NUMERIC(10) NOT NULL,PAYMENT_NUMBER NUMERIC(10) NOT NULL,
PAYMENT_DATE DATE NOT NULL ,PAYMENT_AMOUNT NUMERIC(20) NOT NULL,
PRIMARY KEY(LOAN_NUMBER,PAYMENT_NUMBER),FOREIGN KEY(LOAN_NUMBER) REFERENCES LOAN(LOAN_NUMBER)) ;

